### PR TITLE
Added release notes for Version 0.4

### LINKED ISSUE #97: Package new release to include latest patch change (version 0.3.2)
#90 bumped the scipy version to <1.11.0 but these changes have yet to be packaged and published to Pypi.

Would it be possible to cut a release and publish it?

Many thanks!

### PR DESCRIPTION
**Pull request by oliverfunk**
Closes #97 

@esc I used the script you linked to in the issue to generate the change log. Please review so a new release can be cut. Many of us need the new version now.

Thanks!

Oliver

### CODE REVIEW

**Comment by oliverfunk** [comment]
@esc btw I used

```
gitlog2changelog.py --token=<token> --beginning=bd99bb687814269e95c3ef2aedf23144c1436eff --repo=numba/numba-scipy --digits=2 --summary
```

That commit hash was the one version 0.3 branched from.

**Comment by esc** [comment]
@oliverfunk thank you, noted! Your efforts here are much appreciated and will hopefully enable a release soon. I just looked at my schedule and will hopefully have some time during the week starting 8th of April.

**Comment by esc** [comment]
> @oliverfunk thank you, noted! Your efforts here are much appreciated and will hopefully enable a release soon. I just looked at my schedule and will hopefully have some time during the week starting 8th of April.

Picking this up now.

**Comment by esc** [comment]
having trouble re-running Azure -- will open/close.

**Comment by esc** [comment]
Building with 3.12 may be potentially broken:

```
 💣 zsh» python setup.py develop
/Users/esc/git/numba-scipy/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/Users/esc/git/numba-scipy/setup.py", line 11, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/esc/git/numba-scipy/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/Users/esc/git/numba-scipy/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/esc/git/numba-scipy/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser' 💣 zsh» python setup.py develop
/Users/esc/git/numba-scipy/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/Users/esc/git/numba-scipy/setup.py", line 11, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/esc/git/numba-scipy/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/Users/esc/git/numba-scipy/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/esc/git/numba-scipy/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'??
```

**Comment by esc** [comment]
Versioneer to support 3.12 is here: https://github.com/numba/numba-scipy/pull/102

**Comment by esc** [comment]
FYI: with #103 merged, I took the liberty to rebase this onto `main` at 03f9c2ac47

**Comment by esc** [comment]
Looking at the list of PRs in the changelog, I think some of them have already been added to 0.3.1 so the changelog might need to be fixed up some more.

**Comment by esc** [comment]
> Looking at the list of PRs in the changelog, I think some of them have already been added to 0.3.1 so the changelog might need to be fixed up some more.

It looks like a bunch of PRs were backported for the 0.3.1 release -- as a result I would argue that these would need to be removed from the changelog entry for 0.4

Screenshot 2024-04-09 at 16 27 57

**Comment by esc** [comment]
> > Looking at the list of PRs in the changelog, I think some of them have already been added to 0.3.1 so the changelog might need to be fixed up some more.
> 
> It looks like a bunch of PRs were backported for the 0.3.1 release -- as a result I would argue that these would need to be removed from the changelog entry for 0.4
> 
> Screenshot 2024-04-09 at 16 27 57

Those changes have been made in  c977a14

**Comment by esc** [comment]
#102 was merged and will be included in 0.4 -- I've updated the changelog accordingly.

**Comment by esc** [comment]
@oliverfunk together with @sklam we decided to not include an upgrade to 3.12 in 0.4 and instead release what we have now and include 3.12 in 0.5 -- apparently this also needs scipy in 1.12 as a minimum, which is higher than what 0.4 supports.

**Review by sklam — APPROVED** [review]
LGTM

**Comment by oliverfunk** [comment]
@esc amazing! Thank you.
Yeah supporting py3.12 in 0.5 makes sense.
Cheers!

**Comment by esc** [comment]
> @esc amazing! Thank you. Yeah supporting py3.12 in 0.5 makes sense. Cheers!

No worries. FWIW: this project is open to additional maintainers, in case that "tickles your fancy". 😅

**Pull request merged**
