### PR TITLE
Add reference documentation for scipy.special functions.

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title, also moves code generation scripts to "scripts"

### CODE REVIEW

**Comment by stuartarchibald** [comment]
@seibert please could you review as convenient, thanks.

**Comment by stuartarchibald** [comment]
@person142 Good point. Done.

**Comment by stuartarchibald** [comment]
@person142 thanks for the review. @seibert could you please take a look?

**Comment by seibert** [comment]
this also looks fine, and I assume #25 will fix the failure on 32-bit

**Pull request merged**
