### PR TITLE
generate_special_function_declarations against scipy 1.4.1

### PR DESCRIPTION
**Pull request by dgarnier**
Scipy dropped some signatures in scipy.special and added ellipk, voigt_profile, and wrightomega.

Just re-ran the generator script against my installation.

### CODE REVIEW

**Comment by person142** [comment]
Dupe of https://github.com/numba/numba-scipy/pull/37 I believe.

**Comment by esc** [comment]
@person142 I just had a look at this and it seems like there is overlap between #37 and this. But not all changes in this PR are also in #37 --is that correct?

**Comment by dgarnier** [comment]
> @person142 I just had a look at this and it seems like there is overlap between #37 and this. But not all changes in this PR are also in #37 --is that correct?

Hmm... actually I think #37 does have all the same changes.. just for some reason they are arranged differently.

**Comment by dgarnier** [comment]
Dupe of #37.

**Pull request closed without merging**
