### PR TITLE
Update versioneer to 3.12

### PR DESCRIPTION
**Pull request by esc**
using `versioneer install --vendor` in a 3.12 env

### CODE REVIEW

**Review by sklam — COMMENTED** [review]
Code changes are good but GHA CI is not happy!? Why are jobs cancelled?

**Comment by esc** [comment]
> Code changes are good but GHA CI is not happy!? Why are jobs cancelled?

Not sure yet, seems like one failed job causes the others to fail too, have to triage some more.

**Comment by esc** [comment]
@sklam seems like the CI system isn't quite ready to be bumped to 3.12 just yet, I reverted the bump and seems like all tests are passing now.

The GHA works like this: we build a package on 3.10 and then test on 3.8 -- 3.11 . When adding 3.12 to the mix we end up with:

```
Run conda install -c numba python=3.12 numba>=0.45 'scipy>=1.4,<1.11.0' 'numpy>=1.22.0' flake8 pytest
```

to setup the test env. But then attempting to install the build artifact in this environment yields:

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides numpy-base 1.23.3 py310h375b286_0 needed by numpy-1.23.3-py310hac523dd_0
 ```

Which is odd as the `py310` string in the package name suggests mamba is attempting to install a NumPy for Python 3.10 but on 3.12?

My suggestion here is to divide and conquer. Since this PR only affects the vendored versioneer files -- which seem to pass on the current CI config -- and these files are auto-generated -- so would suggest to get this merged up and refactor and fixup support for 3.12 in a subsequent PR?

**Review by sklam — APPROVED** [review]
I agree that we should divide and conqueur.

**Pull request merged**
