### PR TITLE
Add basic support for `scipy.special`

### PR DESCRIPTION
**Pull request by person142**
### What is in this PR

This adds scalar overloads for the functions in `scipy.special` which are 

- present in `cython_special`
- have a single return value
- have only float or integer arguments (i.e. no complex arguments yet).

For a more explicit idea of what those functions are, check `signatures.json`.

### How does it work

The approach is:

1. Generate a big map from function name/types to function pointers in `cython_special`
2. Generate a list of all functions and their signatures
3. At module import time iterate over the list from (2) and add overloads using the map from (1)

In practice (1) is split into two maps; the first one is in `function_pointers.pyx` and is made as small as possible to minimize compile time (it was pretty egregious otherwise). The map/list are generated using the script `special_function_pointers.py`.

### Further discussion

As it stands, this approach involves adding a Cython build-time dependency. I am taking this approach over fiddling with the `__pyx_capi__` of `cython_special` because the structure of `__pyx_capi__` is, as far as I know, a private Cython implementation detail.

Things which are not included in this PR, but that are maybe desirable for the future:

- Casts. There is currently no upcasting from e.g. `float32` to `float64`, which users probably expect since that's how ufuncs work. I have an experimental branch for this in `numba_special`, but it seemed better to keep the initial PR here simpler.
- Vector kernels. I'm not sure if this is a desirable feature since it's easy to vectorize a scalar kernel and there are several possible ways to do that vectorization (e.g. parallelized or not).

Anyway, I'm sure the final shape of this could end up looking quite different, but I wanted to get some code up to keep the momentum going. Also I can get everything to run locally, but I'm sure some CI appeasing will be needed.

**Edit**: also note that the diff isn't as giant as it seems; Github appears to be ignoring the `binary` attribute on the autogenerated files. Locally I get:

```
$ git diff --stat HEAD~1 HEAD .gitattributes                            |   3 +
 .gitignore                                |   3 +
 numba_scipy/special/__init__.py           |   3 +
 numba_scipy/special/function_pointers.pyx | Bin 0 -> 22459 bytes
 numba_scipy/special/overloads.py          |  26 +++++++++
 numba_scipy/special/signatures.json       | Bin 0 -> 24322 bytes
 numba_scipy/special/signatures.py         | Bin 0 -> 53326 bytes
 numba_scipy/special/types.py              |  12 ++++
 numba_scipy/tests/test_special.py         |  70 +++++++++++++++++++++++
 setup.py                                  |  24 +++++++-
 special_function_pointers.py              | 159 +++++++++++++++++++++++++++++++++++++++++++++++++++
 11 files changed, 299 insertions(+), 1 deletion(-)
```

### CODE REVIEW

**Comment by stuartarchibald** [comment]
Thanks for submitting this PR @person142, much appreciated.

<snip>

> ### Further discussion
> 
> As it stands, this approach involves adding a Cython build-time dependency. I am taking this approach over fiddling with the `__pyx_capi__` of `cython_special` because the structure of `__pyx_capi__` is, as far as I know, a private Cython implementation detail.

I opened https://github.com/cython/cython/issues/3077 against `cython` to see what the devs there have to say about `__pyx_capi__` use, stability etc. I understand your reasoning behind reusing Cython to generate a consistent interface but am also keen to see if it's possible to keep to pure Python.


> Things which are not included in this PR, but that are maybe desirable for the future:
> 
>     * Casts. There is currently no upcasting from e.g. `float32` to `float64`, which users probably expect since that's how ufuncs work. I have an experimental branch for this in `numba_special`, but it seemed better to keep the initial PR here simpler.

Agree, let's get this working first.
 
>     * Vector kernels. I'm not sure if this is a desirable feature since it's easy to vectorize a scalar kernel and there are several possible ways to do that vectorization (e.g. parallelized or not).

Might be possible/desirable to lean on Numba's ufunc mechanisms for this (and the above).

<snip>

**Comment by person142** [comment]
> I opened cython/cython#3077 against cython to see what the devs there have to say about __pyx_capi__ use, stability etc.

In the absence of advice on the Cython side, shall we just bravely move ahead with using `__pyx_capi__`? The approach here is easily adapted since it's just a matter of changing where you grab the pointers from.

**Comment by stuartarchibald** [comment]
> > I opened [cython/cython#3077](https://github.com/cython/cython/issues/3077) against cython to see what the devs there have to say about **pyx_capi** use, stability etc.
> 
> In the absence of advice on the Cython side, shall we just bravely move ahead with using `__pyx_capi__`? The approach here is easily adapted since it's just a matter of changing where you grab the pointers from.

I think that:

1. `<popular internet search engines> "__pyx_capi__"` returns a lot of results, including numerous cases of others doing similar.
2. From 1. I found this https://twitter.com/stefanvdwalt/status/1001982618097811456 and subsequently https://github.com/ashwinvis/cython_capi, so there's clearly interest in and the need to produce this interface. Further it seems to have been around since at least 2012 https://twitter.com/wesmckinn/status/274553271027372033.
3. Whilst 1. and 2. perhaps nod towards the longevity of the interface the concerns raised previously were about stability. Given this has been around so long I anticipate there's reliance on the format and given what is being expressed (C-like prototypes and addresses) the potential for change is probably small.
4. As this PR is essentially doing code generation and using programmatic bindings, it's a question of balancing the risk of binding directly to `__pyx_capi__`, and that potentially changing, against the non-trivial effort required to build, test and ship a package that requires a C toolchain.

I'm of the view that it's worth taking the risk and using  `__pyx_capi__` as going back to a cython generated interface doesn't seem programmatically onerous, just more effort when it comes to packaging.

What are your thoughts on the same?

**Comment by person142** [comment]
Yup, let’s take the risk. At these early stages it’s better to move forward and maybe make mistakes than it is to fret over details. I’ll update this PR and then we can move on to the interesting stuff. :-)

**Comment by stuartarchibald** [comment]
> Yup, let’s take the risk. At these early stages it’s better to move forward and maybe make mistakes than it is to fret over details. I’ll update this PR and then we can move on to the interesting stuff. :-)

Excellent, go for it :) Thanks!

**Comment by person142** [comment]
Closing in favor of https://github.com/numba/numba-scipy/pull/13.

**Pull request closed without merging**
