### PR TITLE
Add contributing doc

### PR DESCRIPTION
**Pull request by stuartarchibald**
As title

### CODE REVIEW

**Comment by seibert** [comment]
Looks reasonable.  Does it need more specific directions about setting up a dev environment?

**Comment by seibert** [comment]
Actually, it looks like once I merge #20, the final link in this file can point to the home of those rendered docs.

**Comment by stuartarchibald** [comment]
@seibert patched up WRT #20 and https://numba-scipy.readthedocs.io/en/latest/developer/contributing.html

**Comment by seibert** [comment]
Looks good!

**Pull request merged**
